_BASE_: "base.yaml"

DATASET:
  PATH: '/storage/shafner/urban_change_detection/OSCD_dataset/preprocessed/'
  TRAIN: ['abudhabi', 'beihai', 'hongkong', 'beirut', 'mumbai']
  TEST: ['dubai', 'chongqing']
