_BASE_: "base.yaml"

THRESH: 0.0
LOGGING: 1
SAVE_MODEL: True

MODEL:
  LOSS_TYPE: 'JaccardLikeLoss'
  IN_CHANNELS: 8

TRAINER:
  LR: 5e-5
  EPOCHS: 1500

DATASET:
  PATH: '/storage/shafner/urban_change_detection/OSCD_dataset/preprocessed/'
  MODE: 'optical' # optical, radar or fusion
  SENTINEL2:
    BANDS: ['B02', 'B03', 'B04', 'B08']
    TEMPORAL_MODE: 'bi-temporal'