_BASE_: "base.yaml"

SEED: 9
THRESH: 0.75
SAVE_MODEL: True

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 28

DATASET:
  MODE: 'fusion'
  SENTINEL1_BANDS: ['VV']
  SENTINEL2_BANDS: ['B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B09', 'B10', 'B11', 'B12']

DATALOADER:
  NUM_WORKERS: 16