_BASE_: "new_base.yaml"

THRESH: 0.0

MODEL:
  IN_CHANNELS: 28

DATASET:
  MODE: 'fusion' # optical, radar or fusion
  SENTINEL1:
    BANDS: ['VV']
  SENTINEL2:
    BANDS: ['B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B09', 'B10', 'B11', 'B12']